var subject = require('./subject.js');
var mock = require('mock-fs');mock({"testPath":{"testFile":"text content","emptyFile":""}});
var testPath = 'testPath';var testFile ='testFile';var doesnotexist = 'doesnotexist';var stillDoesNotExist = 'stillDoesNotExist';var emptyFile = 'emptyFile';
subject.inc(0,'');
subject.inc(-1,'');
subject.inc(1,'');
subject.inc(0,undefined);
subject.inc(-1,undefined);
subject.inc(1,undefined);
subject.fileTest('',testPath+"/"+testFile);
subject.fileTest(testPath,testPath+"/"+testFile);
subject.fileTest(doesnotexist,testPath+"/"+testFile);
subject.fileTest('',testPath+"/"+emptyFile);
subject.fileTest(testPath,testPath+"/"+emptyFile);
subject.fileTest(doesnotexist,testPath+"/"+emptyFile);
subject.fileTest('',testPath+"/"+stillDoesNotExist);
subject.fileTest(testPath,testPath+"/"+stillDoesNotExist);
subject.fileTest(doesnotexist,testPath+"/"+stillDoesNotExist);
subject.fileTest('',testPath+"/"+testFile);
subject.fileTest(testPath,testPath+"/"+testFile);
subject.fileTest(doesnotexist,testPath+"/"+testFile);
subject.fileTest('',doesnotexist+"/"+stillDoesNotExist);
subject.fileTest(testPath,doesnotexist+"/"+stillDoesNotExist);
subject.fileTest(doesnotexist,doesnotexist+"/"+stillDoesNotExist);
subject.normalize('');
subject.normalize('934-901-7747');
subject.normalize('785-502-3255');
subject.format('','','');
subject.format('1-752-159-9624','','');
subject.format('229-444-8746','','');
subject.format('','','foo');
subject.format('1-752-159-9624','','foo');
subject.format('229-444-8746','','foo');
subject.format('','',{"normalize":"foo"});
subject.format('1-752-159-9624','',{"normalize":"foo"});
subject.format('229-444-8746','',{"normalize":"foo"});
subject.blackListNumber('');
subject.blackListNumber('1-184-282-5117');
subject.blackListNumber('470-450-5778');

mock.restore()