var subject = require('./subject.js');
var mock = require('mock-fs');mock({"testPath":{"testFile":"text content","emptyFile":""}});
var testPath = 'testPath';var testFile ='testFile';var doesnotexist = 'doesnotexist';var stillDoesNotExist = 'stillDoesNotExist';var emptyFile = 'emptyFile';
subject.inc(0,'');
subject.inc(-1,'');
subject.inc(1,'');
subject.inc(0,undefined);
subject.inc(-1,undefined);
subject.inc(1,undefined);
subject.fileTest('',testPath+"/"+testFile);
subject.fileTest(testPath,testPath+"/"+testFile);
subject.fileTest(doesnotexist,testPath+"/"+testFile);
subject.fileTest('',testPath+"/"+emptyFile);
subject.fileTest(testPath,testPath+"/"+emptyFile);
subject.fileTest(doesnotexist,testPath+"/"+emptyFile);
subject.fileTest('',testPath+"/"+stillDoesNotExist);
subject.fileTest(testPath,testPath+"/"+stillDoesNotExist);
subject.fileTest(doesnotexist,testPath+"/"+stillDoesNotExist);
subject.fileTest('',testPath+"/"+testFile);
subject.fileTest(testPath,testPath+"/"+testFile);
subject.fileTest(doesnotexist,testPath+"/"+testFile);
subject.fileTest('',doesnotexist+"/"+stillDoesNotExist);
subject.fileTest(testPath,doesnotexist+"/"+stillDoesNotExist);
subject.fileTest(doesnotexist,doesnotexist+"/"+stillDoesNotExist);
subject.normalize('');
subject.normalize('(172) 771-2289 x181');
subject.normalize('321-845-5149');
subject.format('','','');
subject.format('1-988-002-6793','','');
subject.format('514-765-1973','','');
subject.format('','','foo');
subject.format('1-988-002-6793','','foo');
subject.format('514-765-1973','','foo');
subject.blackListNumber('');
subject.blackListNumber('(334) 946-9062 x77511');
subject.blackListNumber('755-255-0778');

mock.restore()